# Generated by Django 5.1.7 on 2025-06-25 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharedError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delete_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("error_text", models.TextField()),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("creator_name", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="ErrorFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("language", models.CharField(blank=True, max_length=50)),
                (
                    "shared_error",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.sharederror",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "shared_error",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.sharederror",
                    ),
                ),
            ],
        ),
    ]
